<?xml version="1.0"?>
<package format="3">
  <name>robot_brain</name>
  <version>0.0.1</version>
  <description>Logique de décision et intelligence du robot</description>
  <maintainer email="votre@email.com">Theo</maintainer>
  <license>Apache License 2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>std_msgs</depend>
  <depend>geometry_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>